language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean bootJar"

addons:
  ssh_known_hosts: mossol.net:22223

before_deploy:
- echo "Preparing for deployment"
- cat ~/.ssh/known_hosts
- openssl aes-256-cbc -K $encrypted_abe9606208ec_key -iv $encrypted_abe9606208ec_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r -e "ssh -p 22223" --delete-after --quiet $TRAVIS_BUILD_DIR amos_doan@mossol.net:~/out
  on:
    branch: master

