language: java
jdk:
    - openjdk8

branches:
    only:
        - master


# Travis CI Cache Activate
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# clean & Build
script: "./gradlew clean build"
