spring:
  profiles:
    active: local

server:
  port: 8181

# slack integrations
rtmUrl: https://slack.com/api/rtm.start?token={token}&simple_latest&no_unreads
slackBotToken: <defined as environment variable in the production machine>
slackApi: https://slack.com/api
logging.level:
  me.ramswaroop: DEBUG

# line integration
line:
  secret: <defined as environment variable in the production machine>
  token: <defined as environment variable in the production machine>

# central dogma
centraldogma:
  hosts:
  - mossol.net:7373

retrofit:
  baseUrl: https://api.line.me
  connectionTimeOutMills: 5000
  maxRetry: 3
